### ISSUE TITLE
Serial port read error on windows

### ISSUE THREAD

**Issue by jaxsonpd** [jaxsonpd/better-serial#1]
On windows when running the application in "dumb" mode as soon as any key is pressed an error occurs:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "com_tx.py", line 113, in com_tx_dumb_thread_entry
AttributeError: 'bytes' object has no attribute 'encode'
```

This issue is not present on linux.

**Comment by jaxsonpd** [comment]
I believe this is caused by the windows version of getchar() returning a byte string not a string meaning it does not need to be encoded to begin with.

**Comment by jaxsonpd** [comment]
Issue resolved in linked pull request,
